import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useForm } from "../../lib/hooks/useForm";
import Signup from "../../components/SignUp/Signup";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CMPS | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Signup />
    </>
  );
}
